
name: doctests

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y pandoc
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: |
        python -m pip install -r docs/requirements.txt
    - run: |
        python -m sphinx docs/ docs/_build/html/
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/